# Generated by Django 4.2.6 on 2023-10-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmdevice', to='home.device')),
            ],
        ),
        migrations.CreateModel(
            name='YearSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_schedule', models.CharField(default='pm', max_length=500)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearpm', to='preventivemaintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_schedule', models.CharField(default='pm', max_length=500)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekpm', to='preventivemaintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='SixMonthSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sixmonth_schedule', models.CharField(default='pm', max_length=500)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sixmonthpm', to='preventivemaintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_schedule', models.CharField(default='pm', max_length=500)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonpm', to='preventivemaintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_schedule', models.CharField(default='pm', max_length=500)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthpm', to='preventivemaintenance.pm')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_schedule', models.CharField(default='pm', max_length=500)),
                ('pm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailypm', to='preventivemaintenance.pm')),
            ],
        ),
    ]
