# Generated by Django 4.2.6 on 2023-10-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=800)),
                ('amount_consumption_per_patient', models.IntegerField(default=0)),
                ('price_per_consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_device', to='home.device')),
            ],
        ),
        migrations.CreateModel(
            name='BuyBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppc_brand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty', models.IntegerField()),
                ('special_warranty', models.IntegerField()),
                ('special_warranty_description', models.CharField()),
                ('buy_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_brand', to='buy.buydevice')),
            ],
        ),
    ]
